name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v2.1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Initialize StartOS developer key
        run: start-cli init-key

      - name: Build the service package
        run: |
          make

      - name: Setting package ID and title from the manifest
        id: package
        run: |
          PACKAGE_ID=$(awk -F"'" '/id:/ {print $2}' startos/manifest/index.ts)
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          FIRST_S9PK=$(ls ${PACKAGE_ID}_*.s9pk | head -n 1)
          echo "first_s9pk=$FIRST_S9PK" >> $GITHUB_ENV
          start-cli s9pk inspect "$FIRST_S9PK" manifest > manifest.json
          echo "package_title=$(jq -r '.title' manifest.json)" >> $GITHUB_ENV
        shell: bash

      - name: Generate sha256 checksums
        run: |
          PACKAGE_ID=${{ env.package_id }}
          printf "\nSHA256SUMS:\n"
          for s9pk in ${PACKAGE_ID}_*.s9pk; do
            sha256sum "$s9pk" | tee "${s9pk}.sha256"
          done
        shell: bash

      - name: Generate changelog
        run: |
          PACKAGE_ID=${{ env.package_id }}
          echo "## Release Notes" > change-log.txt
          jq -r '.releaseNotes.en_US' manifest.json >> change-log.txt
          echo "## SHA256 Hashes" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum ${PACKAGE_ID}_*.s9pk >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.package_title }} ${{ github.ref_name }}
          prerelease: true
          body_path: change-log.txt
          files: |
            ./${{ env.package_id }}_*.s9pk
            ./${{ env.package_id }}_*.s9pk.sha256

      - name: Publish to Registry
        env:
          S9USER: ${{ secrets.S9USER }}
          S9PASS: ${{ secrets.S9PASS }}
          S9REGISTRY: ${{ secrets.S9REGISTRY }}
        run: |
          if [[ -z "$S9USER" || -z "$S9PASS" || -z "$S9REGISTRY" ]]; then
            echo "Publish skipped: missing registry credentials."
          else
            for s9pk in ${{ env.package_id }}_*.s9pk; do
              start-cli s9pk publish https://$S9USER:$S9PASS@$S9REGISTRY "$s9pk"
            done
          fi
